// <auto-generated />
using System;
using Eos.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eos.Data.EF.Postgres.Migrations
{
    [DbContext(typeof(EosContext))]
    partial class EosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Eos.Abstracts.Entities.GlobalItem", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParentIndex")
                        .HasColumnType("integer");

                    b.HasKey("ParentId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("GlobalItems");
                });

            modelBuilder.Entity("Eos.Abstracts.Entities.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ItemId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Title")
                        .HasName("IX_Items.Title");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Eos.Abstracts.Entities.GlobalItem", b =>
                {
                    b.HasOne("Eos.Abstracts.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eos.Abstracts.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Eos.Abstracts.Entities.Item", b =>
                {
                    b.HasOne("Eos.Abstracts.Entities.Item", "Parent")
                        .WithMany("OwnerItems")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
